return {
	"init.lua",
	"_preload.lua",
	"semver.lua",
	"pkg.lua",
	"pack.lua",
	"repo.lua",
	"repoapis/debug.lua",
	"repoapis/github.lua",
	"packapis/git.lua",
	"packapis/file.lua",
	"packapis/git.lua",
	"builders/generic.lua",
	"builders/premake.lua",
	"builders/cmake.lua",
	"builders/msbuild.lua",
	"builders/gmake.lua",
	"defaults.lua"
}